### ISSUE TITLE
`dist` Fails to Install `astral-sh/uv` - Pulls `source.tar.gz` instead

### ISSUE THREAD

**Issue by Shackelford-Arden** [ekristen/distillery#120]
# Error

```
❯ dist install --log-level=debug astral-sh/uv
   • distillery/v1.0.6
   • source: github
   • app: astral-sh/uv
   • os: linux
   • arch: amd64
   • determining latest version
   • version: 0.5.12
DEBU[0000] file scoring sorted ! type: 0, scored: {sha256.sum 30}  discover=binary
DEBU[0000] file scoring sorted ! type: 0, scored: {uv-installer.ps1 27}  discover=binary
DEBU[0000] file scoring sorted ! type: 0, scored: {uv-installer.sh 27}  discover=binary
DEBU[0000] file scoring sorted ! type: 1, scored: {uv-x86_64-unknown-linux-gnu.tar.gz 101}  discover=binary
DEBU[0000] file scoring sorted ! type: 1, scored: {uv-x86_64-unknown-linux-musl.tar.gz 101}  discover=binary
DEBU[0000] file scoring sorted ! type: 1, scored: {uv-arm-unknown-linux-musleabihf.tar.gz 39}  discover=binary
DEBU[0000] file scoring sorted ! type: 1, scored: {uv-armv7-unknown-linux-gnueabihf.tar.gz 39}  discover=binary
DEBU[0000] file scoring sorted ! type: 1, scored: {uv-armv7-unknown-linux-musleabihf.tar.gz 39}  discover=binary
DEBU[0000] file scoring sorted ! type: 1, scored: {uv-i686-unknown-linux-gnu.tar.gz 39}  discover=binary
DEBU[0000] file scoring sorted ! type: 1, scored: {uv-i686-unknown-linux-musl.tar.gz 39}  discover=binary
DEBU[0000] file scoring sorted ! type: 1, scored: {uv-powerpc64-unknown-linux-gnu.tar.gz 39}  discover=binary
DEBU[0000] file scoring sorted ! type: 1, scored: {uv-powerpc64le-unknown-linux-gnu.tar.gz 39}  discover=binary
DEBU[0000] file scoring sorted ! type: 1, scored: {uv-s390x-unknown-linux-gnu.tar.gz 39}  discover=binary
DEBU[0000] file scoring sorted ! type: 1, scored: {uv-x86_64-apple-darwin.tar.gz 19}  discover=binary
DEBU[0000] file scoring sorted ! type: 1, scored: {uv-x86_64-pc-windows-msvc.zip 14}  discover=binary
DEBU[0000] file scoring sorted ! type: 1, scored: {source.tar.gz 10}  discover=binary
DEBU[0000] file scoring sorted ! type: 1, scored: {uv-aarch64-unknown-linux-gnu.tar.gz 9}  discover=binary
DEBU[0000] file scoring sorted ! type: 1, scored: {uv-aarch64-unknown-linux-musl.tar.gz 9}  discover=binary
DEBU[0000] file scoring sorted ! type: 1, scored: {uv-i686-pc-windows-msvc.zip -48}  discover=binary
DEBU[0000] file scoring sorted ! type: 1, scored: {uv-aarch64-apple-darwin.tar.gz -73}  discover=binary
DEBU[0000] file scoring sorted ! type: 4, scored: {source.tar.gz.sha256 105}  discover=checksum
DEBU[0000] file scoring sorted ! type: 4, scored: {uv-arm-unknown-linux-musleabihf.tar.gz.sha256 70}  discover=checksum
DEBU[0000] file scoring sorted ! type: 4, scored: {uv-armv7-unknown-linux-gnueabihf.tar.gz.sha256 70}  discover=checksum
DEBU[0000] file scoring sorted ! type: 4, scored: {uv-armv7-unknown-linux-musleabihf.tar.gz.sha256 70}  discover=checksum
DEBU[0000] file scoring sorted ! type: 4, scored: {uv-i686-unknown-linux-gnu.tar.gz.sha256 70}  discover=checksum
DEBU[0000] file scoring sorted ! type: 4, scored: {uv-i686-unknown-linux-musl.tar.gz.sha256 70}  discover=checksum
DEBU[0000] file scoring sorted ! type: 4, scored: {uv-powerpc64-unknown-linux-gnu.tar.gz.sha256 70}  discover=checksum
DEBU[0000] file scoring sorted ! type: 4, scored: {uv-powerpc64le-unknown-linux-gnu.tar.gz.sha256 70}  discover=checksum
DEBU[0000] file scoring sorted ! type: 4, scored: {uv-s390x-unknown-linux-gnu.tar.gz.sha256 70}  discover=checksum
DEBU[0000] file scoring sorted ! type: 4, scored: {uv-x86_64-unknown-linux-gnu.tar.gz.sha256 65}  discover=checksum
DEBU[0000] file scoring sorted ! type: 4, scored: {uv-x86_64-unknown-linux-musl.tar.gz.sha256 65}  discover=checksum
DEBU[0000] file scoring sorted ! type: 4, scored: {uv-aarch64-unknown-linux-gnu.tar.gz.sha256 40}  discover=checksum
DEBU[0000] file scoring sorted ! type: 4, scored: {uv-aarch64-unknown-linux-musl.tar.gz.sha256 40}  discover=checksum
DEBU[0000] file scoring sorted ! type: 4, scored: {uv-i686-pc-windows-msvc.zip.sha256 30}  discover=checksum
DEBU[0000] file scoring sorted ! type: 4, scored: {uv-x86_64-apple-darwin.tar.gz.sha256 30}  discover=checksum
DEBU[0000] file scoring sorted ! type: 4, scored: {uv-x86_64-pc-windows-msvc.zip.sha256 25}  discover=checksum
DEBU[0000] file scoring sorted ! type: 4, scored: {uv-aarch64-apple-darwin.tar.gz.sha256 5}  discover=checksum
   • downloading assets
DEBU[0000] file already downloaded: /home/heimdal/.cache/distillery/downloads/archive-216021642
DEBU[0000] file already downloaded: /home/heimdal/.cache/distillery/downloads/checksum-216021608
DEBU[0000] verifying checksum
panic: runtime error: index out of range [0] with length 0 [recovered]
        panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.main.func1()
        github.com/ekristen/distillery/main.go:29 +0x54
panic({0xaf6780?, 0xc0004a7110?})
        runtime/panic.go:785 +0x132
github.com/ekristen/distillery/pkg/checksum.CompareHashWithChecksumFile({0xc0004ae5d0, 0x22}, {0xc0004b37c0, 0x3b}, {0xc0004b39c0, 0x3c}, 0xba4258)
        github.com/ekristen/distillery/pkg/checksum/compare.go:60 +0x529
github.com/ekristen/distillery/pkg/provider.(*Provider).verifyChecksum(0xc00029d790)
        github.com/ekristen/distillery/pkg/provider/provider.go:735 +0x1d1
github.com/ekristen/distillery/pkg/provider.(*Provider).Verify(0xc00029d790)
        github.com/ekristen/distillery/pkg/provider/provider.go:561 +0x18
github.com/ekristen/distillery/pkg/provider.(*Provider).CommonRun(0xc00029d790, {0xc467f0?, 0xc00024c000?})
        github.com/ekristen/distillery/pkg/provider/provider.go:81 +0x7f
github.com/ekristen/distillery/pkg/source.(*GitHub).Run(0xc00029d790, {0xc467f0, 0xc00024c000})
        github.com/ekristen/distillery/pkg/source/github.go:78 +0x92
github.com/ekristen/distillery/pkg/commands/install.Execute(0xc0002ce300)
        github.com/ekristen/distillery/pkg/commands/install/install.go:108 +0x1170
github.com/urfave/cli/v2.(*Command).Run(0xc00023a6e0, 0xc0002ce300, {0xc0002a2480, 0x3, 0x3})
        github.com/urfave/cli/v2@v2.27.5/command.go:276 +0x7e2
github.com/urfave/cli/v2.(*Command).Run(0xc0002d2160, 0xc0002ce080, {0xc000022100, 0x4, 0x4})
        github.com/urfave/cli/v2@v2.27.5/command.go:269 +0xa65
github.com/urfave/cli/v2.(*App).RunContext(0xc000180200, {0xc467f0, 0xc00024c000}, {0xc000022100, 0x4, 0x4})
        github.com/urfave/cli/v2@v2.27.5/app.go:333 +0x5a5
main.main()
        github.com/ekristen/distillery/main.go:56 +0x4fa
```

# Steps to Replicate

Attempt to install `uv`:

```shell
dist install astral-sh/uv
```

May try and poke around myself, but wanted to get this out there while I've got it in front of me :)

**Comment by ekristen** [comment]
Thanks for the report. I'll take a look, I've been working on updates today.

**Comment by ekristen** [comment]
There's two issues here. First is that there's failure to check for an empty line in the checksum file, which I can fix and throw an error for. The second issues is a bit more problematic, it will require an adjustment to the scoring system.
